services:
  - type: web
    name: django-react-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn myprojectas.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myprojectas.settings
      - key: SECRET_KEY
        value: your-secret-key
    staticPublishPath: staticfiles
