# Generated by Django 5.2.1 on 2025-06-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date')},
        ),
    ]
